name: hexlet-linter

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install_dependencies
        run: |
          pip install poetry
          make install
      - name: Run-linter
        run: make lint
